GET http://localhost:3500/api/estudiantes

###
POST http://localhost:3500/api/estudiantes
Content-Type: application/json

{
  "nombre": "Ana Araya",
  "correo": "ana@correo.de",
  "materias" : {
      "nombre": "español",
      "nota": 95,
      "comentario" : "Tiene facilidad para la lectura"
  }
}

###
DELETE http://localhost:3500/api/estudiantes/60d4d1c1e4594c2928c41309

###
PUT  http://localhost:3500/api/estudiantes/60d4d39c5d61452820906c1f
Content-Type: application/json

{
  "nombre": "Ana Araya",
  "correo": "ana@correo.de"
}

//----Materias

###
GET http://localhost:3500/api/materias/60d4e27204365e500cd9da98

###
POST http://localhost:3500/api/materias/60d5d1561a143b362839bbb5
Content-Type: application/json

{
  "nombre": "ciencias",
  "nota": 89,
  "comentario": "Puede mejorar"
}

###
DELETE  http://localhost:3500/api/materias/60d4e27204365e500cd9da98/60d4e27204365e500cd9da99

###
PUT  http://localhost:3500/api/materias/60d5d1561a143b362839bbb5/60d5d19f1a143b362839bbb7
Content-Type: application/json

{
  "nota": 95,
  "comentario": "Excelente por el esfuerzo"
}